package meta

// Code generated by proto_to_meta.php — DO NOT EDIT MANUALLY
// Source: /home/hoover/workspace/api/script/project.proto, message: Dict

import (
	"fmt"
	"strings"

	"github.com/light2000/laravel-modeler-generator/common"
	"github.com/light2000/laravel-modeler-generator/proto"
)

type Dict struct {
	*proto.Dict
	Options []*Option
	// Add your custom fields below
	Project *Project
}

func FromProtoDict(p *proto.Dict, project *Project) *Dict {
	if p == nil {
		return nil
	}
	mustSnakeCode("FromProtoDict", p.Id, p.Code)
	dict := &Dict{
		Dict:    p,
		Project: project,
	}
	project.MapDict[p.Id] = dict
	if p.Options != nil {
		dict.Options = make([]*Option, 0, len(p.Options))
		for idx, it := range p.Options {
			dict.Options = append(dict.Options, FromProtoOption(idx, it, dict, project))
		}
	}

	return dict
}

func (dict *Dict) Snake() string {
	return dict.Code
}

func (dict *Dict) Class() string {
	return common.ToCamel(dict.Snake())
}

func (dict *Dict) OptionSnakeArray() []string {
	opts := make([]string, 0, len(dict.Options))
	for _, option := range dict.Options {
		opts = append(opts, option.Snake())
	}
	return opts
}

func (dict *Dict) OptionPhpArray() string {
	return fmt.Sprintf("['%s']", strings.Join(dict.OptionSnakeArray(), "', '"))
}

func (dict *Dict) IsGlobal() bool {
	return dict.ModuleId == ""
}

func (dict *Dict) Module() *Module {
	if dict.IsGlobal() {
		return nil
	}
	if _, ok := dict.Project.MapModules[dict.ModuleId]; !ok {
		panic(fmt.Sprintf("dict %s module %s not found", dict.Id, dict.ModuleId))
	}

	return dict.Project.MapModules[dict.ModuleId]
}

func (dict *Dict) Namespace() string {
	if dict.IsGlobal() {
		return dict.Project.GlobalEnumLayout.Namespace
	}
	return dict.Module().Namespace.EnumNamespace
}

func (dict *Dict) OutputPath() string {
	if dict.IsGlobal() {
		return dict.Project.GlobalEnumLayout.OutputPath
	}
	return dict.Module().Namespace.EnumOutputPath
}
