package meta

// Code generated by proto_to_meta.php — DO NOT EDIT MANUALLY
// Source: /home/hoover/workspace/api/script/project.proto, message: Item

import (
	"fmt"

	"github.com/light2000/laravel-modeler-generator/common"
	"github.com/light2000/laravel-modeler-generator/proto"
)

type Item struct {
	*proto.Item
	Attrs     []*Attribute
	Indexes   []*Index
	Relations []*Relation
	// Add your custom fields below
	Project *Project
	Module  *Module
	Middle  bool
}

func FromProtoItem(p *proto.Item, module *Module, project *Project, isPivot bool) *Item {
	if p == nil {
		return nil
	}
	mustSnakeCode("FromProtoItem", p.Id, p.Code)

	m := &Item{
		Item:    p,
		Module:  module,
		Project: project,
		Middle:  isPivot,
	}

	project.MapItems[p.Id] = m

	if p.Attrs != nil {
		m.Attrs = make([]*Attribute, 0, len(p.Attrs))
		for _, it := range p.Attrs {
			m.Attrs = append(m.Attrs, FromProtoAttribute(it, m, module, project))
		}
	}

	// 处理索引
	if p.Indexes != nil {
		m.Indexes = make([]*Index, 0, len(p.Indexes))
		for _, it := range p.Indexes {
			m.Indexes = append(m.Indexes, FromProtoIndex(it, m, project))
		}
	}

	if p.Relations != nil {
		m.Relations = make([]*Relation, 0, len(p.Relations))
		for _, it := range p.Relations {
			m.Relations = append(m.Relations, FromProtoRelation(it, m, module, project))
		}
	}

	return m
}

// TODO 转成常量字符串
func (item *Item) MigrationTime() string {
	return item.Project.BuildTime()
}

func (item *Item) Snake() string {
	return item.Code
}

func (item *Item) MorphMapKey() string {
	return item.Snake()
}

func (item *Item) Var() string {
	return common.ToLowerCamel(item.Class())
}

func (item *Item) Vars() string {
	return fmt.Sprintf("%sList", item.Var())
}

func (item *Item) Class() string {
	return common.ToCamel(item.Snake())
}

func (item *Item) IsNormalFake() bool {
	return !item.Middle
}

func (item *Item) IsHasSequenceFakeField() bool {
	return len(item.SequenceFakeAttrs()) > 0
}

func (item *Item) ModelNamespace() string {
	if item.Middle {
		return item.Project.PivotLayout.ModelNamespace
	}
	return item.Module.Namespace.ModelNamespace
}

func (item *Item) ModelOutputPath() string {
	if item.Middle {
		return item.Project.PivotLayout.ModelOutputPath
	}
	return item.Module.Namespace.ModelOutputPath
}

func (item *Item) FactoryNamespace() string {
	if item.Middle {
		return item.Project.PivotLayout.FactoryNamespace
	}
	return item.Module.Namespace.FactoryNamespace
}

func (item *Item) FactoryOutputPath() string {
	if item.Middle {
		return item.Project.PivotLayout.FactoryOutputPath
	}
	return item.Module.Namespace.FactoryOutputPath
}

func (item *Item) MigrationOutputPath() string {
	if item.Middle {
		return item.Project.PivotLayout.MigrationOutputPath
	}
	return item.Module.Namespace.MigrationOutputPath
}

func (item *Item) SeederNamespace() string {
	if item.Middle {
		panic(fmt.Sprintf("seeder namespace is not supported for pivot item: %s", item.Name))
	}
	return item.Module.Namespace.SeederNamespace
}

func (item *Item) SeederOutputPath() string {
	if item.Middle {
		panic(fmt.Sprintf("seeder output path is not supported for pivot item: %s", item.Name))
	}
	return item.Module.Namespace.SeederOutputPath
}

func (item *Item) SequenceFakeAttrs() []*Attribute {
	attrs := make([]*Attribute, 0)
	for _, attr := range item.Attrs {
		if attr.IsSequenceFakeField() {
			attrs = append(attrs, attr)
		}
	}
	return attrs
}

func (item *Item) Hidden() []*Attribute {
	hidden := make([]*Attribute, 0)
	for _, attr := range item.Attrs {
		if attr.IsHidden() {
			hidden = append(hidden, attr)
		}
	}
	return hidden
}

func (item *Item) RelationItems() []*Item {
	items := make([]*Item, 0)
	seen := make(map[string]struct{})
	for _, relation := range item.Relations {
		if relation.TargetItemId != "" {
			if _, ok := seen[relation.TargetItemId]; !ok {
				seen[relation.TargetItemId] = struct{}{}
				items = append(items, item.Project.MapItems[relation.TargetItemId])
			}
		}

		if len(relation.MorphTargets) > 0 {
			for _, morphTarget := range relation.MorphTargets {
				if _, ok := seen[morphTarget.TargetItemId]; ok {
					continue
				}
				seen[morphTarget.TargetItemId] = struct{}{}
				items = append(items, item.Project.MapItems[morphTarget.TargetItemId])
			}
		}

		if relation.PivotId != "" {
			if _, ok := seen[relation.PivotId]; !ok {
				seen[relation.PivotId] = struct{}{}
				items = append(items, item.Project.MapItems[relation.PivotId])
			}
		}
	}
	return items
}

func (item *Item) DictUsed() []*Dict {
	dicts := make([]*Dict, 0)
	seen := make(map[string]struct{})
	for _, attr := range item.Attrs {
		if attr.DictId != "" {
			if _, ok := seen[attr.DictId]; !ok {
				seen[attr.DictId] = struct{}{}
				dicts = append(dicts, attr.Dict())
			}
		}
	}
	return dicts
}

func (item *Item) HasRelationSeeder() bool {
	if !item.HasSeeder {
		return false
	}
	for _, relation := range item.Relations {
		if relation.IsSelfRelation() {
			return true
		}
		if relation.IsBelongsTo() {
			return true
		}
		if relation.IsManyToManySeederSide() {
			return true
		}
		if relation.IsMorphTo() {
			return true
		}
	}
	return false
}

func (item *Item) Timestamps() bool {
	return item.HasCreatedAt && item.HasUpdatedAt
}

func (item *Item) MorphAble() string {
	if !item.Middle {
		panic(fmt.Sprintf("morph able is not supported: %s", item.Name))
	}
	for _, attr := range item.Attrs {
		if attr.Behavior == proto.AttributeBehavior_ATTRIBUTE_BEHAVIOR_MORPH_ID {
			return attr.MorphAble()
		}
	}

	panic(fmt.Sprintf("morph able is not supported: %s", item.Name))
}

func (item *Item) HasStaticDefValue() bool {
	for _, attr := range item.Attrs {
		if attr.HasStaticDefValue() {
			return true
		}
	}
	return false
}

func (item *Item) HasModule() bool {
	return nil != item.Module
}

func (item *Item) HasSets() bool {
	for _, attr := range item.Attrs {
		if attr.IsSets() {
			return true
		}
	}
	return false
}
