package meta

// Code generated by proto_to_meta.php — DO NOT EDIT MANUALLY
// Source: /home/hoover/workspace/api/script/project.proto, message: Project

import (
	"path/filepath"
	"strings"

	"github.com/light2000/laravel-modeler-generator/proto"
)

type PivotLayoutConfig struct {
	*proto.PivotLayoutConfig
	ModelOutputPath   string
	FactoryOutputPath string
}

type GlobalEnumLayoutConfig struct {
	*proto.GlobalEnumLayoutConfig
	OutputPath string
}

type Project struct {
	*proto.Project
	Modules      []*Module
	PivotItems   []*Item
	Dictionaries []*Dict
	Namespaces   []*Namespace
	// Add your custom fields below
	MapItems         map[string]*Item
	MapAttributes    map[string]*Attribute
	MapDict          map[string]*Dict
	MapRelations     map[string]*Relation
	MapModules       map[string]*Module
	MapIndexes       map[string]*Index
	MapNamespaces    map[string]*Namespace
	PrevProject      *Project
	Psr4Map          map[string]string
	PivotLayout      *PivotLayoutConfig
	GlobalEnumLayout *GlobalEnumLayoutConfig
}

func normalizeNamespacePrefix(namespace string) string {
	s := strings.ReplaceAll(namespace, "/", "\\")
	if s != "" && !strings.HasSuffix(s, "\\") {
		s += "\\"
	}
	return s
}

func normalizeOutputPath(path string) string {
	s := strings.ReplaceAll(path, "\\", "/")
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "./")
	return strings.Trim(s, "/")
}

func namespaceSuffix(fullNamespace, prefix string) string {
	full := normalizeNamespacePrefix(fullNamespace)
	base := normalizeNamespacePrefix(prefix)
	if !strings.HasPrefix(full, base) {
		return ""
	}
	return strings.TrimSuffix(strings.TrimPrefix(full, base), "\\")
}

func (project *Project) ResolveOutputPathByNamespace(namespace string) string {
	target := normalizeNamespacePrefix(namespace)
	if target == "" || len(project.Psr4Map) == 0 {
		return ""
	}
	bestKey := ""
	bestPath := ""
	for key, path := range project.Psr4Map {
		k := normalizeNamespacePrefix(key)
		if strings.HasPrefix(target, k) && len(k) > len(bestKey) {
			bestKey = k
			bestPath = path
		}
	}
	if bestKey == "" {
		return ""
	}
	suffix := namespaceSuffix(target, bestKey)
	basePath := normalizeOutputPath(bestPath)
	if suffix == "" {
		return basePath
	}
	return filepath.ToSlash(filepath.Join(basePath, strings.ReplaceAll(suffix, "\\", "/")))
}

func FromProtoProject(p *proto.Project) *Project {
	if p == nil {
		panic("proto project is nil")
	}
	project := &Project{
		Project:       p,
		Namespaces:    make([]*Namespace, 0, len(p.Namespaces)),
		MapItems:      make(map[string]*Item),
		MapAttributes: make(map[string]*Attribute),
		MapDict:       make(map[string]*Dict),
		MapRelations:  make(map[string]*Relation),
		MapModules:    make(map[string]*Module),
		MapIndexes:    make(map[string]*Index),
		MapNamespaces: make(map[string]*Namespace),
		PrevProject:   nil,
		Psr4Map:       make(map[string]string),
	}

	if p.PivotLayoutConfig == nil {
		p.PivotLayoutConfig = &proto.PivotLayoutConfig{}
	}
	if p.GlobalEnumLayoutConfig == nil {
		p.GlobalEnumLayoutConfig = &proto.GlobalEnumLayoutConfig{}
	}
	project.PivotLayout = &PivotLayoutConfig{PivotLayoutConfig: p.PivotLayoutConfig}
	project.GlobalEnumLayout = &GlobalEnumLayoutConfig{GlobalEnumLayoutConfig: p.GlobalEnumLayoutConfig}

	if p.Namespaces != nil {
		project.Namespaces = make([]*Namespace, 0, len(p.Namespaces))
		for _, it := range p.Namespaces {
			namespace := FromProtoNamespace(it, project)
			project.Namespaces = append(project.Namespaces, namespace)
			project.MapNamespaces[it.Id] = namespace
		}
	}

	if p.Dictionaries != nil {
		project.Dictionaries = make([]*Dict, 0, len(p.Dictionaries))
		for _, it := range p.Dictionaries {
			dict := FromProtoDict(it, project)
			project.Dictionaries = append(project.Dictionaries, dict)
		}
	}

	if p.PivotItems != nil {
		project.PivotItems = make([]*Item, 0, len(p.PivotItems))
		for _, it := range p.PivotItems {
			item := FromProtoItem(it, nil, project, true)
			project.PivotItems = append(project.PivotItems, item)
		}
	}

	if p.Modules != nil {
		project.Modules = make([]*Module, 0, len(p.Modules))
		for _, it := range p.Modules {
			module := FromProtoModule(it, project)
			project.Modules = append(project.Modules, module)
		}
	}

	return project
}

func (project *Project) GetItemById(id string) (item *Item) {
	return project.MapItems[id]
}

func (project *Project) GetAttributeById(id string) (attr *Attribute) {
	return project.MapAttributes[id]
}

func (project *Project) GetRelationById(id string) (relation *Relation) {
	return project.MapRelations[id]
}

func (project *Project) GetModuleByItemId(itemId string) *Module {
	for _, module := range project.Modules {
		for _, item := range module.Items {
			if item.Id == itemId {
				return module
			}
		}
	}
	panic("module not found: " + itemId)
}

func (project *Project) BuildTime() string {
	return "2000_01_01_000000"
}

func (project *Project) MigrationDirs() []string {
	var dir string
	dirs := make([]string, 0)
	seen := make(map[string]struct{})
	for _, module := range project.Modules {
		dir = module.Namespace.MigrationOutputPath
		if _, ok := seen[dir]; !ok {
			seen[dir] = struct{}{}
			dirs = append(dirs, dir)
		}
	}
	dir = project.PivotLayout.MigrationOutputPath
	if _, ok := seen[dir]; !ok {
		seen[dir] = struct{}{}
		dirs = append(dirs, dir)
	}
	return dirs
}
